### ISSUE TITLE
scheme attribute for media:credit and media:rating

### ISSUE THREAD

**Issue by ksridhar** [amagimedia/metadata#21]
in https://github.com/amagimedia/metadata/blob/main/amgrss_schemas/amgrss_xpaths_description.csv as per specification at https://www.rssboard.org/media-rss#media-credit and https://www.rssboard.org/media-rss#media-rating. The master example at https://github.com/amagimedia/metadata/blob/dfa0453e3b7e65ae59364a243c03965ab30ebcee/amgrss_schemas/amgrss_master.xml#L59 and https://github.com/amagimedia/metadata/blob/dfa0453e3b7e65ae59364a243c03965ab30ebcee/amgrss_schemas/amgrss_master.xml#L16 mention them (i.e. the `scheme` attribute)

**Comment by shashi-banger** [comment]
For `rating` also scheme is fixed to http://www.ebu.ch/metadata/ontologies/skos/ebu_ParentalGuidanceCodeCS.rdf
